// src/applicants/enums/track.enum.ts
export enum InternshipTrack {
  FRONT_END_WEB_DEVELOPMENT = 'FRONT_END_WEB_DEVELOPMENT',
  BACK_END_DEVELOPMENT = 'BACK_END_DEVELOPMENT',
  UI_UX_DESIGN = 'UI_UX_DESIGN',
  VIDEO_EDITING = 'VIDEO_EDITING',
  DATA_SCIENCE = 'DATA_SCIENCE',
  EMBEDDED_SYSTEMS_ROBOTICS = 'EMBEDDED_SYSTEMS_ROBOTICS',
}
